### ISSUE TITLE
pyasn1.error.SubstrateUnderrunError: 37-octet short

### ISSUE THREAD

**Issue by egberts** [ernw/insinuator-snippets#6]
I get this error with client.py with Python 2.7.13 on CentOS6.9 visiting https://nt.com/OCSP

```
 $ ./client.py 
Traceback (most recent call last):
  File "./client.py", line 119, in <module>
    response = decode(response, OCSPResponse())
  File "./client.py", line 106, in decode
    ocspResponse = decoder.decode(data, asn1Spec=spec)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 784, in __call__
    '%d-octet short' % (length - len(substrate))
pyasn1.error.SubstrateUnderrunError: 37-octet short
```

**Comment by TayC710** [comment]
Do you work out this issue?

**Comment by egberts** [comment]
No.   I have since moved on given that my platform is Python3+ and bleeding edge.

The pressure to not pursue this by the inclusion of very old legacy stuff was too great.

Was a bit stymied by the lack of a simple demonstrator or code example.
